"""Multi-model debug team for a generated app.

Every available Groq model is asked what is wrong. The three strongest are then
asked to reconcile the reports into one agreed set of fixes, so a single model
cannot talk the others into changing working code.

Only fixes that survive a re-scan are kept.
"""
from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path

# Groq's catalogue changes often; unknown ids are skipped at runtime.
CANDIDATES = [
    "llama-3.3-70b-versatile",
    "openai/gpt-oss-120b",
    "openai/gpt-oss-20b",
    "moonshotai/kimi-k2-instruct",
    "deepseek-r1-distill-llama-70b",
    "meta-llama/llama-4-scout-17b-16e-instruct",
    "meta-llama/llama-4-maverick-17b-128e-instruct",
    "llama-3.1-8b-instant",
    "gemma2-9b-it",
]

LEADERS = 3           # the three that reconcile the reports
MAX_ROUNDS = 3
TIMEOUT = 180


def _key() -> str:
    k = os.environ.get("GROQ_API_KEY", "")
    if not k:
        raise SystemExit("no GROQ_API_KEY")
    return k


def call(model: str, system: str, user: str, temperature: float = 0.2,
         max_tokens: int = 6000) -> str | None:
    body = {"model": model, "temperature": temperature, "max_tokens": max_tokens,
            "messages": [{"role": "system", "content": system},
                         {"role": "user", "content": user}]}
    req = urllib.request.Request(
        "https://api.groq.com/openai/v1/chat/completions",
        data=json.dumps(body).encode(), method="POST")
    req.add_header("Authorization", "Bearer " + _key())
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
            d = json.loads(r.read().decode())
        return d["choices"][0]["message"]["content"]
    except (urllib.error.HTTPError, Exception):  # noqa: BLE001
        return None


def _json_of(raw: str | None) -> dict | None:
    if not raw:
        return None
    m = re.search(r"\{.*\}", raw, re.S)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except Exception:  # noqa: BLE001
        return None


AUDIT = """You review a single-file HTML app that was generated by another AI.

A headless browser clicked every control. Here is what responded to nothing:
{dead}
Controls with no handler at all:
{missing}
JavaScript errors:
{errors}

Reply with JSON only:
{{"real_bugs": [{{"control": "<label>", "why": "<what is broken>"}}],
  "false_positives": ["<label>"], "confidence": 0.0-1.0}}

Be strict. A control that is intentionally inert (a placeholder, a disabled
state, a container) is a false positive. Only report a control as a real bug
if a user clicking it would expect something to happen.
"""


def audit(models: list[str], scan: dict) -> dict:
    """Ask every model independently; majority vote decides what is real."""
    user = AUDIT.format(dead=json.dumps(scan.get("dead", []))[:3000],
                        missing=json.dumps(scan.get("missing", []))[:2000],
                        errors=json.dumps(scan.get("errors", []))[:2000])
    reports: dict[str, dict] = {}
    for m in models:
        got = _json_of(call(m, AUDIT, user, temperature=0.1, max_tokens=2000))
        if got:
            reports[m] = got
    if not reports:
        return {"confirmed": [], "reports": {}}

    # key on the whole control label, not just the tag, or every button
    # collapses into a single vote
    def key_of(label: str) -> str:
        s = re.sub(r"\s+", " ", str(label)).strip().lower()
        return s[:60]

    votes: dict[str, int] = {}
    for r in reports.values():
        for b in r.get("real_bugs", []) or []:
            k = key_of(b.get("control", ""))
            if k:
                votes[k] = votes.get(k, 0) + 1
    need = max(2, (len(reports) // 2) + 1)
    confirmed = [lbl for lbl, n in votes.items() if n >= need]

    # map a confirmed vote back onto the scanner's exact labels so the repair
    # step is told about real controls and not just about "button"
    exact: dict[str, str] = {}
    for dcl in scan.get("dead", []) or []:
        exact.setdefault(key_of(dcl.split("(")[0]), dcl.split("(")[0].strip())
    confirmed = [exact.get(key_of(c), c) for c in confirmed]
    print(f"[team] {len(reports)}/{len(models)} models answered | "
          f"votes {votes} | need {need}")
    return {"confirmed": confirmed, "reports": reports}


SCOPE = {
 "minimal":  "Change only the listed controls. Leave every other line alone.",
 "targeted": "You may refactor the script block and any component the listed controls belong to. Keep the layout, styling and every other feature identical.",
 "rewrite":  "The listed controls could not be fixed in place. Rewrite the whole script block so the entire app works end to end. Keep the same HTML structure, ids, styling and features.",
}

FIX = """You repair one self-contained HTML file for a Windows desktop app.

Confirmed broken controls (a majority of reviewers agree these do nothing):
{confirmed}

Repair scope for this round: {scope}

Repair rules:
- Return the COMPLETE file as JSON: {{"html": "<!DOCTYPE html> ... </html>"}}
- Stay inside the scope above. Do not redesign or restyle.
- Wire up event handlers so each listed control does the obvious thing using
  the app's existing state, styling and patterns.
- Do not remove controls. Do not add external scripts, fonts or images.
- The file must stay completely offline.
"""


def fix(leaders: list[str], scan: dict, confirmed: list[str],
        html: str, mode: str = "minimal") -> tuple[str, str] | None:
    """Three leaders propose; the first to return parseable, complete HTML wins."""
    user = FIX.format(confirmed=json.dumps(confirmed)[:2000], html=html[:60000],
                      scope=SCOPE.get(mode, SCOPE["minimal"]))
    if mode == "rewrite":
        # a full rewrite needs the biggest models first, not the first responder
        order = [m for m in leaders if "120b" in m or "70b" in m or "kimi" in m] + list(leaders)
        seen, ordered = set(), []
        for m in order:
            if m not in seen:
                seen.add(m); ordered.append(m)
        leaders = ordered
    for m in leaders:
        raw = call(m, FIX, user, temperature=0.1 if mode == "rewrite" else 0.15,
                   max_tokens=24000)
        got = _json_of(raw)
        if got and isinstance(got.get("html"), str):
            out = got["html"]
            if "<html" in out and "</html>" in out and len(out) > 1500:
                print(f"[team] {m} produced a repair ({len(out)} bytes)")
                return out, m
    return None