"""Multi-model debug team for a generated app.

Every available Groq model is asked what is wrong. The three strongest are then
asked to reconcile the reports into one agreed set of fixes, so a single model
cannot talk the others into changing working code.

Only fixes that survive a re-scan are kept.
"""
from __future__ import annotations

import json
import os
import re
import ai
from pathlib import Path

# Groq's catalogue changes often; unknown ids are skipped at runtime.
# Checked against the live catalogue: the prompt-guard models are classifiers
# and whisper is audio, so only three of the eleven can be asked for a repair.
CANDIDATES = [
    "openai/gpt-oss-120b",
    "qwen/qwen3.8-27b",
    "openai/gpt-oss-20b",
]

LEADERS = 3           # the three that reconcile the reports
MAX_ROUNDS = 3
TIMEOUT = 180


def call(model: str, system: str, user: str, temperature: float = 0.2,
         max_tokens: int = 6000, reasoning: bool = False) -> str | None:
    try:
        import ai
        return ai.chat(model, system, user, temperature, max_tokens,
                       reasoning=reasoning)
    except Exception as e:  # noqa: BLE001
        last_error[0] = str(e)[:200]
        return None


last_error = [""]


def _json_of(raw: str | None) -> dict | None:
    if not raw:
        return None
    m = re.search(r"\{.*\}", raw, re.S)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except Exception:  # noqa: BLE001
        return None


# ---------------------------------------------------------------- styling guard
# The generator makes apps that look good. A repair must never restyle
# anything, so styling is compared before and after and the patch is thrown
# away if it differs. This is enforced here rather than asked for in a prompt,
# because a model cannot be relied on to obey a style instruction.

def _styles(html: str) -> list[str]:
    import re as _re
    return [m.group(0) for m in _re.finditer(r"<style[^>]*>.*?</style>", html, _re.S | _re.I)]


def _inline_style(html: str) -> list[str]:
    import re as _re
    return sorted(_re.findall(r'style\s*=\s*"[^"]*"', html, _re.I))


def _visual(html: str) -> str:
    """Structure and class names carry the look too, so they are part of the
    identity we refuse to let a repair change."""
    import re as _re
    body = _re.sub(r"<script.*?</script>", "", html, flags=_re.S | _re.I)
    body = _re.sub(r"<style.*?</style>", "", body, flags=_re.S | _re.I)
    return (tuple(_styles(html)), tuple(_inline_style(html)),
            tuple(sorted(set(_re.findall(r'class\s*=\s*"([^"]*)"', body)))))


def styling_unchanged(before: str, after: str) -> bool:
    return _visual(before) == _visual(after)



AUDIT = """You review a single-file HTML app that was generated by another AI.

A headless browser clicked every control. Here is what responded to nothing:
{dead}
Controls with no handler at all:
{missing}
JavaScript errors:
{errors}

Reply with JSON only:
{{"real_bugs": [{{"control": "<label>", "why": "<what is broken>"}}],
  "false_positives": ["<label>"], "confidence": 0.0-1.0}}

Be strict. A control that is intentionally inert (a placeholder, a disabled
state, a container) is a false positive. Only report a control as a real bug
if a user clicking it would expect something to happen.
"""


def audit(models: list[str], scan: dict) -> dict:
    """Ask every model independently; majority vote decides what is real."""
    user = AUDIT.format(dead=json.dumps(scan.get("dead", []))[:3000],
                        missing=json.dumps(scan.get("missing", []))[:2000],
                        errors=json.dumps(scan.get("errors", []))[:2000])
    # every model is asked at the same time; sequential calls made a single
    # round take as long as nine round trips
    from concurrent.futures import ThreadPoolExecutor
    reports: dict[str, dict] = {}
    with ThreadPoolExecutor(max_workers=min(9, len(models) or 1)) as pool:
        futures = {pool.submit(call, m, AUDIT, user, 0.1, 2000, False): m for m in models}
        for fut, m in futures.items():
            try:
                got = _json_of(fut.result())
            except Exception:  # noqa: BLE001
                got = None
            if got:
                reports[m] = got
    if not reports:
        return {"confirmed": [], "reports": {}}

    # key on the whole control label, not just the tag, or every button
    # collapses into a single vote
    def key_of(label: str) -> str:
        s = re.sub(r"\s+", " ", str(label)).strip().lower()
        return s[:60]

    votes: dict[str, int] = {}
    for r in reports.values():
        for b in r.get("real_bugs", []) or []:
            k = key_of(b.get("control", ""))
            if k:
                votes[k] = votes.get(k, 0) + 1
    need = max(2, (len(reports) // 2) + 1)  # 2 of 3 is a majority
    confirmed = [lbl for lbl, n in votes.items() if n >= need]

    # map a confirmed vote back onto the scanner's exact labels so the repair
    # step is told about real controls and not just about "button"
    exact: dict[str, str] = {}
    for dcl in scan.get("dead", []) or []:
        exact.setdefault(key_of(dcl.split("(")[0]), dcl.split("(")[0].strip())
    confirmed = [exact.get(key_of(c), c) for c in confirmed]
    print(f"[team] {len(reports)}/{len(models)} models answered | "
          f"votes {votes} | need {need}")
    return {"confirmed": confirmed, "reports": reports}


SCOPE = {
 "minimal":  "Change only the listed controls. Leave every other line alone.",
 "targeted": "You may refactor the script block and any component the listed controls belong to. Keep the layout, styling and every other feature identical.",
 "rewrite":  "The listed controls could not be fixed in place. Rewrite the whole script block so the entire app works end to end. Keep the same HTML structure, ids, styling and features.",
}

FIX = """You repair one self-contained HTML file for a Windows desktop app.

Confirmed broken controls (a majority of reviewers agree these do nothing):
{confirmed}

Repair scope for this round: {scope}

Repair rules:
- Return the COMPLETE file as JSON: {{"html": "<!DOCTYPE html> ... </html>"}}
- Stay inside the scope above. Do not redesign or restyle.
- Wire up event handlers so each listed control does the obvious thing using
  the app's existing state, styling and patterns.
- Do not remove controls. Do not add external scripts, fonts or images.
- NEVER alter the CSS: the <style> block, any style="" attribute, or any class
  name. The app already looks good. Only the HTML structure and the script may
  change, and only where a confirmed control needs a handler.
- The file must stay completely offline.
"""


def fix(leaders: list[str], scan: dict, confirmed: list[str],
        html: str, mode: str = "minimal") -> tuple[str, str] | None:
    """Three leaders propose; the first to return parseable, complete HTML wins."""
    user = FIX.format(confirmed=json.dumps(confirmed)[:2000], html=html[:60000],
                      scope=SCOPE.get(mode, SCOPE["minimal"]))
    if mode == "rewrite":
        # a full rewrite needs the biggest models first, not the first responder
        order = [m for m in leaders if "120b" in m or "27b" in m] + list(leaders)
        seen, ordered = set(), []
        for m in order:
            if m not in seen:
                seen.add(m); ordered.append(m)
        leaders = ordered
    for m in leaders:
        # A full single-file app is ~30 KB, so the reply needs room. Reasoning
        # tokens come out of the same budget and were silently eating it, which
        # is why repairs came back empty.
        raw = call(m, FIX, user, temperature=0.1 if mode == "rewrite" else 0.15,
                   max_tokens=40000)
        if raw is None:
            print(f"[team] {m} call failed or returned nothing")
            continue
        got = _json_of(raw)
        if not got or not isinstance(got.get("html"), str):
            print(f"[team] {m} returned no usable JSON")
            continue
        out = got["html"]
        if "<html" not in out or "</html>" not in out or len(out) <= 1500:
            print(f"[team] {m} returned an incomplete document ({len(out)} bytes)")
            continue
        if not styling_unchanged(html, out):
            print(f"[team] {m} changed the styling - rejected")
            continue
        print(f"[team] {m} produced a repair ({len(out)} bytes), styling intact")
        return out, m
    return None