"""Write the Discord article for a published tool.

The article is the long-form version of the product card: what problem it
solves, what is in each edition, and how to get it. It is generated by the
model that built the app, so it stays honest about what shipped, and falls
back to a deterministic write-up if the model is unavailable.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

import discord_data as dd

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
OUT = DATA / "articles.json"

FALLBACK = """**{title}** — {blurb}

**Why it exists**
{tag_title} is one of those small irritations that eats a little attention every
single day. This is a single-purpose tool for it: no setup, no sign-in, no
network calls. Open the page and it works.

**What the free edition does**
Everything you need for the job itself. It runs straight in the browser and
your data never leaves your device.

**What the full edition adds**
The full edition is a native Windows app: a real installer, a desktop shortcut,
and no browser tab to hunt down. It also carries the extra features listed on
the product page.

**Get it**
- Free: {free_url}
- Full edition: {buy_url}

One new tool lands every month. Use `/vote` in the server to pick what comes
next.
"""


def clean(body: str) -> str:
    """Trim to something that reads like prose, not a model transcript."""
    text = (body or "").strip()
    if not text:
        return ""
    # drop markdown fences and any leading "here is..." preamble
    text = re.sub(r"^```[a-z]*\n|\n```$", "", text).strip()
    text = re.sub(r"^(here(?:'s| is).*?:)\s*", "", text, flags=re.I)
    # a heading that just repeats the title adds nothing
    text = re.sub(r"^#\s+.+\n+", "", text, count=1)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text[:6000]


def fallback_article(tool: dict) -> str:
    tag = (tool.get("tags") or ["utility"])[0]
    tag_title = str(tag).replace("-", " ").strip().capitalize() or "This tool"
    return FALLBACK.format(
        title=tool.get("title", "Slingshot Tool"),
        blurb=tool.get("blurb", "A small, focused tool."),
        tag_title=tag_title,
        free_url=tool.get("free_url") or dd.SITE_URL,
        buy_url=tool.get("buy_url") or f"{dd.SITE_URL}/checkout.html",
    )


def main() -> int:
    slug = (sys.argv[1] if len(sys.argv) > 1 else "").strip()
    if not slug:
        stage = dd._load(dd.PUBLISHED, {})
        slug = stage.get("slug") if isinstance(stage, dict) else ""
    if not slug:
        print("[article] no product to write about")
        return 0

    tool = dd.tool_by_slug(slug)
    if not tool:
        print(f"[article] {slug} is not a live tool")
        return 0

    body = ""
    if os.environ.get("GROQ_API_KEY"):
        body = clean(_model_article(tool))
    if not body:
        body = fallback_article(tool)
        print("[article] using the deterministic write-up")

    dd.save_article(tool["base"], body)
    print(f"[article] wrote {len(body)} characters for {tool['base']}")
    return 0


def _model_article(tool: dict) -> str:
    """Ask the builder model for the write-up; any failure is not fatal."""
    try:
        import providers
        model = os.environ.get("ARTICLE_MODEL") or "openai/gpt-oss-20b"
        body = providers.groq_chat(
            model=model,
            system=("You write short product announcements for a Discord "
                    "server. Plain markdown, no emoji, no preamble, never "
                    "invent features that were not described to you."),
            user=(
                "Write a short article for this tool. Cover what problem it "
                "solves, what the free edition does, and what the full "
                f"edition adds. Under 220 words.\n\n"
                f"Title: {tool.get('title')}\n"
                f"Summary: {tool.get('blurb')}\n"
                f"Tags: {', '.join(tool.get('tags') or [])}\n"
                f"Price: ${tool.get('price', 0):.2f}\n"
                f"Free download: {tool.get('free_url')}"),
            temperature=0.4,
            max_tokens=700,
        )
        return body if isinstance(body, str) else ""
    except Exception as e:  # noqa: BLE001
        print(f"[article] model unavailable ({e})")
        return ""


if __name__ == "__main__":
    raise SystemExit(main())
